"""empty message

Revision ID: 298b465a3542
Revises: e9cbdc84e666
Create Date: 2023-12-03 02:57:21.548014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '298b465a3542'
down_revision = 'e9cbdc84e666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
