"""empty message

Revision ID: 787dec4e1ea9
Revises: 2947085a2f9c
Create Date: 2023-12-03 02:53:49.893770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787dec4e1ea9'
down_revision = '2947085a2f9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('name')
        batch_op.drop_column('create_at')

    # ### end Alembic commands ###
